import localFont from "next/font/local";
import "@/styles/globals.css";

const wantedSans = localFont({
  src: "../fonts/WantedSansVariable.woff2",
  preload: true,
  style: "normal",
  display: "swap",
  weight: "400 1000",
  variable: "--font-wanted-sans",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${wantedSans.variable}`}>
        {children}
      </body>
    </html>
  );
}
